### ISSUE TITLE
tabulka - zpřístupnovací modul na vložení

### ISSUE THREAD

**Issue by Chlupova** [NLCR/PerMonik-zpristupnovaci-modul#1]
opravená tabulka na vložení do zpřístupňovacího modulu ke stažení zde:

https://docs.google.com/spreadsheets/d/1ArgR6queQvSD-wc8NEmFLb-p1tIHJSvr/edit#gid=1498753020

**Comment by Kretiss** [comment]
Vyřešeno v https://github.com/NLCR/evidence.periodik/issues/234
